#! /bin/sh
chmod -x *.pdf *.jpg *.ltx bidi.dtx
xelatex bidi.dtx
xelatex bidi.dtx
makeindex -s gind.ist -o bidi.ind  bidi.idx
makeindex -s gglo.ist -o bidi.gls  bidi.glo}
xelatex bidi.dtx

xelatex bidi-doc.ltx
xelatex bidi-doc.ltx
xelatex bidi-doc.ltx
mkdir -p doc/xelatex/bidi source/xelatex/bidi tex/xelatex/bidi 
mkdir bidi
mv *.sty *.cls *.def  bidi.tex tex/xelatex/bidi
# not currently built/cropped from bidi-logo.tex
cp bidi-logo.pdf bibitem.pdf doc/xelatex/bidi
mv bidi.pdf  bidi-doc.pdf *.tex README.txt  doc/xelatex/bidi
cp *.jpg  doc/xelatex/bidi
mv bidi.ins source/xelatex/bidi
cp *.ltx bidi.dtx source/xelatex/bidi
zip -r bidi-tds doc/xelatex/bidi source/xelatex/bidi tex/xelatex/bidi 
mv bidi-tds.zip bidi.tds.zip
mv doc/xelatex/bidi/*.pdf doc/xelatex/bidi/*.jpg doc/xelatex/bidi/README.txt source/xelatex/bidi/*.ltx source/xelatex/bidi/bidi.dtx tex/xelatex/bidi/bibitem.pdf bidi
zip -r bidi-ctan.zip bidi.tds.zip bidi
rm -r doc source tex bidi
rm *.idx *.out *.toc *.gls *.ilg *.ind *.glo *.hd *.aux *.log bidi.tds.zip
